# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
#
# If you want to be able to access a string config[:site_title], for example:
#
# site_title:
#   name: Site Title
#   type: string
#   default: My Site
#
# 'name' is the name that appears in the edit form
#
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
#
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned

site_title:
  name: Site Title
  default: Just a forum
  type: string

autowrap_thread_threshold:
  name: Subthreads will be auto-wrapped as soon as they hit this depth
  default: 8
  type: integer

autowrap_thread_value:
  name: Thread wrap depth
  default: 5
  type: integer

# TODO: replace with admin view
default_homepage_threads:
  name: Number of threads at homepage for guests
  default: 50
  type: integer

recaptcha_public:
  name: Recaptcha public key (set to empty string to disable captcha at all)
  default:
  type: string

recaptcha_private:
  name: Recaptcha private key
  default:
  type: string

activity_minutes:
  name: Show activity for this number of minutes
  default: 10
  type: integer

# site_description:
#   name: Description for Google
#   default: Lots of Awesomeness Here
#   type: text

# secret:
#   name: Secret Password for Accessing Secret Areas
#   default: secret
#   type: password
